[package]
name = "three-ten-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
zip = "6.0.0"
macros = { path = "./macros" }
